### ISSUE TITLE
Missing JSXText method

### ISSUE THREAD

**Issue by maor-benami** [Qard/astring-jsx#7]
```
/node_modules/astring-jsx/index.js:14
        this[child.type](child, state);
                        ^

TypeError: this[child.type] is not a function
    at Object.JSXElement (/node_modules/astring-jsx/index.js:14:25)
    at Object.ReturnStatement (/node_modules/astring-jsx/node_modules/astring/dist/astring.js:421:28)
    at Object.BlockStatement (/node_modules/astring-jsx/node_modules/astring/dist/astring.js:300:25)
    at Object.MethodDefinition (/node_modules/astring-jsx/node_modules/astring/dist/astring.js:664:29)
    at Object.BlockStatement (/node_modules/astring-jsx/node_modules/astring/dist/astring.js:300:25)
    at Object.ClassDeclaration (/node_modules/astring-jsx/node_modules/astring/dist/astring.js:549:8)
    at Object.Program (/node_modules/astring-jsx/node_modules/astring/dist/astring.js:274:24)
    at astring (/node_modules/astring-jsx/node_modules/astring/dist/astring.js:1021:28)
    at astringJsx (/node_modules/astring-jsx/index.js:74:10)
```

**Comment by barelyhuman** [comment]
Fixed in: https://github.com/barelyhuman/astring-jsx/commit/fd7f61f77d6816aa02e6b3a60887772a95e002f9
